### ISSUE TITLE
remove old entry of FEConf

### ISSUE THREAD

**Issue by kishu** [tech-conferences/conference-data#154]
In this PR
https://github.com/tech-conferences/conference-data/pull/124

I requested update entry of FEConf date to 2018-11-03

But old entry of FEConf display yet.

this commit seems unapplied.

https://github.com/tech-conferences/conference-data/pull/124/commits/df87b15bf74fcdb39bcef3208e033d1a8c5dc501

![image](https://user-images.githubusercontent.com/13197080/46272740-6c219180-c58d-11e8-9db4-6076a61414ce.png)

**Comment by trivikr** [comment]
The old entry of FEConf was removed in PR #124 itself, and confirmed that there's only one entry now https://github.com/tech-conferences/conference-data/blob/9878517f4bc68fc57794ff22d371f009526c6b56/conferences/2018/javascript.json#L1725-L1732

cc @nimzco on why the old data is appearing on the website.

**Comment by nimzco** [comment]
Fixed!
Sorry about that. That happens when we update a conference start date to a different month. :/
In these cases I have to remove by hand from http://api-confs-tech.herokuapp.com/admin 🙈
