### ISSUE TITLE
Support email as a kind of CFP address

### ISSUE THREAD

**Issue by Toparvion** [tech-conferences/conference-data#1748]
Currently `CFP URL` field assumes that the value is a web page address. But there are conferences where talk proposals can be sent in a free form by email. For example, community-driven SnowOne conference. In corresponding PR (#1747) its CFP URL is incorrect (irrelevant fields are omitted):
```json
{
  "cfpUrl": "http://cfp@snowone.ru",
}
```
Perhaps the field should support URI instead of URL.

**Comment by cookieguru** [comment]
The URL should be a place that tells prospective speakers what topics would be considered, important dates, and other instructions on how to submit, even if the actual submission takes place in another format

**Comment by cgrail** [comment]
I agree with that. We won't support URLs for the CFP.
