### ISSUE TITLE
Please add CFML as a topic

### ISSUE THREAD

**Issue by Adrian-Sanchez** [tech-conferences/conference-data#1837]
ColdFusion Markup Language, more commonly known as CFML, is a scripting language for web development.
CFML runs on a server-side web application server like Lucee or Adobe ColdFusion.

Similar to what PHP, ASP.NET, Ruby on Rails, and others would do, it allows you to render dynamic web sites with a variety aggregation and helper features to output to a client.

**Comment by cgrail** [comment]
I don't think CFML has such a great audience. In that case you could also add the conference with the topic ```general```

**Comment by scottsteinbeck** [comment]
Hello @cgrail, 

We actually have a decent size audience of developers which is growing daily, I agree there have been some assumptions made about ColdFusion in the past but in recent time with the growing popularity of lucee (open source cfml) and a growing open source community our audience has grown to around 3700+ members. ColdFusion is built on top of Java and is, therefore, an easy transition for Java devs making the switch to web development. We currently have about 5-6 large conferences a year and a number of free online presentations and free/paid workshops. 

We would be very appreciative if you could reconsider making it its own category, it would definitely help us to get the word out about all our great content!

**Comment by MordantWastrel** [comment]
@cgrail One could hardly blame you for that view, but there are entire development shops (like ours, and we're hardly unique) that work exclusively with CFML and Lucee. I don't know what the bar is one needs to clear, but we're going to have conferences anyway, so I don't know what the price of adding one additional topic really is that would make this a prohibitive move.

**Comment by dbelanger** [comment]
Hey @cgrail , don't discount the CF audience so soon.  Our yearly conferences include: 3 US, 1 European, 1 Latin American and 1 Indian.  The language itself has both a commercial and open source engine. 

One last thing: Your site has also been promoted on the CF "Modernize or die" podcast because, well, we appreciate all languages, not just the "popular" ones.  We attend all kinds of conferences to stay current and improve our own language in the process.

**Comment by bdw429s** [comment]
@cgrail CFML has a handful of online and in person conferences every year.  Adobe's CF Summit in Vegas brings over 500 people (where there's not Covid!).  Can you please reconsider adding this topic?

**Comment by cgrail** [comment]
I shit. I think I’ve offended a pretty active community. 
@nimzco just added support for cfml. 
https://github.com/tech-conferences/confs.tech/pull/476

Sorry for everything.

**Comment by bdw429s** [comment]
@cgrail It's all good.  We're not offended, just passionate.  Thanks! :)

**Comment by nimzco** [comment]
Wow, what a reaction! It definitely seems that the community is active. 😄 Also I find everyone's reaction super cool and chill, that's really nice to see. 🙏🏼 

Also, that's super cool to hear that confs.tech was shared in the "Modernize or die" podcast, I had no idea.

And, for @cgrail's defense, I also neglected the issue for a long time, sorry about that, should've replied earlier.

**Comment by gpickin** [comment]
@nimzco - Yeah, we spotlight CFML and CFML Related Conferences, but every week we tell them to check out the site for other conferences.

We're going to make sure all of our conferences are put on there!!!
Thanks for making it available!

**Comment by nimzco** [comment]
Awesome!
You can start adding them right away: https://confs.tech/conferences/new `ColdFusion Markup Language` is now available 🙌🏼

**Comment by scottsteinbeck** [comment]
If its possible, could we make a slight tweak to the language name, could you call it `ColdFusion/CFML` its more commonly what we use in other places

**Comment by nimzco** [comment]
Of course, I’ll do that 👍🏼
