### ISSUE TITLE
Double Conference

### ISSUE THREAD

**Issue by melaniedevops** [tech-conferences/conference-data#2219]
Hi!
The conference DevOps Fusion has been postponed from the 18.03 to the 26.08.
Could you please delete the conference on the 18.03?
Also, could you please the additional text from the 26.03, where I described the issue about the postponing.

Thank You!

**Comment by nimzco** [comment]
Hi @melaniedevops, can you remove it from this list, I’ll then remove it from the website (I need to do a manual action for that). https://github.com/tech-conferences/conference-data/blob/6ffc55ffa45ca04302c594902810b023fe73326e/conferences/2020/devops.json

**Comment by melaniedevops** [comment]
Dear @nimzco, it says that I can only edit when I am on the branch. What does that mean? (I am not so familiar with github)

**Comment by nimzco** [comment]
Oh, you need to do that from the command line then. I can’t do it until Wednesday unfortunately because I’m away from home and don’t have access to a computer.
Maybe @cgrail or @prigara could help you do that?

**Comment by cgrail** [comment]
Done https://github.com/tech-conferences/conference-data/pull/2222

**Comment by nimzco** [comment]
Thanks @cgrail ! I’ve removed it from the list 💪🏼
