### ISSUE TITLE
Changes in dates and removals are not fully synced

### ISSUE THREAD

**Issue by prigara** [tech-conferences/conference-data#2267]
Hi,

I've noticed that some of the events that we've recently removed or updated are still visible on the website (trying in the incognito mode, so it's not browser caches).
Examples:
Spring I/O - see twice on the list in May and in October #2261
IcingaConf and OSCamp on Bareos - were removed, still see on the list #2263

Probably some the same issues with other recently updated events - haven't checked them all.

**Comment by nimzco** [comment]
Thanks for the ticket @prigara, unfortunately the backend is not optimized with deletion and updates... I've got to work on that. 😭 

I'll have a look and delete them from https://confs-tech-api.herokuapp.com/admin directly

**Comment by nimzco** [comment]
I went through the last PRs and fixed some duplicates. I'll try to write a script if I get some time 😬

**Comment by nimzco** [comment]
I've tweaked some stuff, we should be good! 👍
