### ISSUE TITLE
Add Code of Conduct checkbox

### ISSUE THREAD

**Issue by FloorD** [tech-conferences/conference-data#2284]
What do yall think about adding a checkbox / flag for conferences that have a Code of Conduct (published on / accessible from the event page)? For plenty of peeps a CoC plays an important role in deciding whether or not to join an event.

**Comment by nimzco** [comment]
That's a good call, you're not the first person to talk about this.
I'll see if I can do that in the upcoming days. The only problem is for existing conferences. :/

**Comment by prigara** [comment]
Thanks for the suggestion. 👍
I wonder if it's true that the wast majority of the events have code of conduct nowadays. Will do some research.

**Comment by nimzco** [comment]
That’s what I would think. But yep, worth investing. 👍🏼

**Comment by FloorD** [comment]
It would be a good signal to conference organizers me thinks.
Happy to do another round of updating (will need to do so anyway as this COVID-19 situation continues to evolve) / make sure the 2021 confs come with CoC check! Thanks for considering :)

**Comment by FloorD** [comment]
Hey team! Would love to revisit this topic, and suggest to introduce markers for:
- Event has CoC (with link to CoC)
- Event offers closed captions
- Event offers interpretation to International sign

**Comment by nimzco** [comment]
Hey @FloorD, that's a great idea.

I've added the fields to the form:
![image](https://user-images.githubusercontent.com/445045/95016234-fe177580-0651-11eb-9ad0-36a46c108c55.png)

And it'll be shown like this on the website when the fields will be available:
![image](https://user-images.githubusercontent.com/445045/95016317-9dd50380-0652-11eb-9f22-d8a9ec01ab85.png)

**Comment by nimzco** [comment]
Let's see if conferences come in with these fields on, and I'll add a filter then.

**Comment by FloorD** [comment]
What would you use formatting wise if I were to bulk edit, @nimzco ?

**Comment by nimzco** [comment]
Hmmm, that's a good question. I think I would do it from my code editor from the repo. I don't see an easy way to bulk edit. 😬

**Comment by FloorD** [comment]
That's my plan. I meant, how would you format both the COC, as well as the accessibility check in json?

**Comment by nimzco** [comment]
Oh I see. You can do it like that: https://github.com/tech-conferences/conference-data/pull/2820/files#diff-3d85b1bd35fb84c79a867bf82d4b7a36R830-R831 😄

**Comment by nimzco** [comment]
Thanks so much for your contribution 🙏
