### ISSUE TITLE
Consider changing default branch name

### ISSUE THREAD

**Issue by FloorD** [tech-conferences/conference-data#2675]
Could you possibly consider changing the default branch name to something like "main"? https://github.com/github/renaming

**Comment by nimzco** [comment]
Hi @FloorD!
Thanks for bringing this to our attention. As [indicated in the repo](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-), and for easier transition, we'll wait until later this year before making this change. ✨

I'll leave the issue open until we rename the branch.

**Comment by nimzco** [comment]
Done!

I’ve updated all repos to have their main branches to main. 🎉
