### ISSUE TITLE
Improve duplicate detection in tests

### ISSUE THREAD

**Issue by nimzco** [tech-conferences/conference-data#28]
- https://github.com/tech-conferences/conference-data/blob/master/scripts/tests/utils.js#L2
- https://github.com/tech-conferences/conference-data/pull/27
- Might be interesting to do it in the backend as well

**Comment by cgrail** [comment]
We could use something like https://github.com/bluzi/travis-buddy to add comments to PRs for failed tests. 

To detect duplicates we could add a Unit Test which is looking for similar conferences maybe with some fuzziness like http://fusejs.io/ to search for similar conference names and log a warning which travis-buddy could then detect and add a comment to a new PR. 

Currently I copy the name of the conference and search for it manually in the repository and check whether there is no entry for that year.

**Comment by nimzco** [comment]
We currently run this test on all branches: https://github.com/tech-conferences/conference-data/blob/master/scripts/tests/conferences.test.js

But there are certainly false positive. Like the one you recently closed. I usually try to add a test when I see a new failing pattern but your suggestion is nice as well.

**Comment by cgrail** [comment]
Can we add https://github.com/bluzi/travis-buddy 

When I have time I can look into a Unit Test for similar conferences.

**Comment by cgrail** [comment]
I think the duplicate detection should now be sufficient enough.
I'm now testing for year, month, url and location. That should cover most cases.
