### ISSUE TITLE
Any proprositon contributions 

### ISSUE THREAD

**Issue by Rebaiahmed** [tech-conferences/conference-data#2882]
Hi I want to ask if there any open propositions of contributions to add here and it's still concerned by hacktooberfest or not?

**Comment by cgrail** [comment]
I've added the ```Hacktoberfest``` topic to the app and data repository:
https://github.com/tech-conferences/confs.tech
https://github.com/tech-conferences/conference-data

I would consider data cleanups or new features as valid entries.

My current wishlist for the app are:
- Support for storing a conference as ```Online``` while creating a new conference
- Support for hybrid conferences where a rule is ```Online``` and has a ```city``` and ```country```
- Support for map on the confs.tech site which shows where the conferences are

**Comment by Rebaiahmed** [comment]
So Can you assign me "storing conference as Online " while creating a new conference? https://confs.tech/conferences/new, and it will be approved with the Hacktoberfest label? 
just more details about it!

**Comment by cgrail** [comment]
Here is the news PR: https://github.com/tech-conferences/confs.tech/issues/473

It will probably consist at least of 3-4 PRs in the different repositories to be able to add this functionality.
