### ISSUE TITLE
How to list hybrid conferences?

### ISSUE THREAD

**Issue by FloorD** [tech-conferences/conference-data#3320]
Hi team, with the rise of hybrid conferences - that both offer an online experience, *and* a physical location - how do we reflect that on confs.tech?

**Comment by cgrail** [comment]
Hi Floor,

like this:

online:
```
{
  "online": true
}
```

on-site:
```
{
  "city": "Paris",
  "country": "France"
}
```

hybrid:
```
{
  "online": true,
  "city": "Paris",
  "country": "France"
}
```

See also:
https://github.com/tech-conferences/confs.tech/pull/475#issuecomment-761801964

**Comment by FloorD** [comment]
Perfection!
