### ISSUE TITLE
LvivJS Page

### ISSUE THREAD

**Issue by 0xflotus** [tech-conferences/conference-data#3345]
I can't read russian or ukrainian, but is this really the conference page at https://lvivjs.org.ua ? See my screenshot below.

https://github.com/tech-conferences/conference-data/blob/4aa02b8fe53bf69298b6fbfa416c1b0e103a4b7f/conferences/2021/javascript.json#L313-L322

![Screenshot_2021-04-20 First Casino ® Украина ᐈ Первое казино онлайн Промокод](https://user-images.githubusercontent.com/26602940/115317510-fd70a780-a17b-11eb-8882-2e31c8bc9f80.png)

**Comment by cgrail** [comment]
Thanks a lot. I've removed it. It was a valid conference at some time.

**Comment by nimzco** [comment]
Oh, that definitely looks wrong. I've tweeted at their account in case: https://twitter.com/ConfsTech/status/1384425262763368452

**Comment by 0xflotus** [comment]
Is LvivJS still a valid conference?

**Comment by nimzco** [comment]
No idea. Their website seems to have been hacked and their Facebook page inactive.
