### ISSUE TITLE
Add link to COVID-19 Policy

### ISSUE THREAD

**Issue by FloorD** [tech-conferences/conference-data#4551]
I'd love for confs.tech to have a link to events' COVID-19 Policies, just like to their Code of Conduct. Ever more events add this info to their event pages.

![Screenshot (401)](https://user-images.githubusercontent.com/1087213/180763405-b8dc389f-b93f-4390-a5ee-5fecc025f8c7.png)

**Comment by nimzco** [comment]
Hi @FloorD, thank you for raising this. I believe we are coming toward the end of all the COVIC-19 related policies (thinking 6+ months) so I'll hold off before implementing such a field. 

I also believe that if people are concerned with this for a specific conference, they will find the info on the conference website. I wouldn't want to have too many information for every conference.

**Comment by cgrail** [comment]
Hi @FloorD 

closing this as it seems no longer relevant. Thanks a lot for raising it.

Best regards,
Christian
