### ISSUE TITLE
Southern California Linux Expo is blocklisted

### ISSUE THREAD

**Issue by kcbraunschweig** [tech-conferences/conference-data#4762]
SCaLE (the Southern California Linux Expo https://www.socallinuxexpo.org/scale/20x ) appears to be blocked when I try to add the call for papers link. This is a conference focused on linux and open source software with many technical tracks including developer focused, devops, systems & infrastructure, kernel development and more. I don't see why this wouldn't be considered a relevant event for software development. Can you unblock us?

**Comment by cgrail** [comment]
Hi @kcbraunschweig 

I've added the conference to our site.
https://github.com/tech-conferences/conference-data/pull/4763
The issue you might have encountered is the list of unwanted conference names like "marketing", "webinar", "hackathon" or "expo". We've received a lot of entries which have not been conferences in the past. Therefor we've blocked some of those terms. In this case it was not right. Sorry for the confusion.
https://github.com/tech-conferences/confs.tech/blob/main/src/scenes/ConferenceForm/utils.ts#L6

Best regards,
Christian
