### ISSUE TITLE
add FOSDEM23 , but what category?

### ISSUE THREAD

**Issue by vielmetti** [tech-conferences/conference-data#4844]
PR to follow (because I have questions about how to categorize a multitrack event that hits a lot of categories).

FOSDEM https://fosdem.org/2023/ is the event. it has 600+ talks over two days in all or nearly all of the categories described. Does it go under "general" or get cross listed?

**Comment by cgrail** [comment]
I prefer General. The individual topics are more for specialized conferences. If I see a conference with 10+ topics I usually merge it into a General entry.

**Comment by cgrail** [comment]
By the way. FOSDEM is already part of the list:
https://github.com/tech-conferences/conference-data/pull/4698
