### ISSUE TITLE
Add ChatGPT Conf

### ISSUE THREAD

**Issue by chatgpt-conference-admin** [tech-conferences/conference-data#5149]
https://chatgpt-conf.vercel.app/

  ChatGPT Conf is the premier virtual conference for AI and NLP enthusiasts, developers, and researchers. Hosted by the advanced AI model ChatGPT, the conference features keynote speakers, panel discussions, and presentations from leading experts in the field. Attendees will have the opportunity to stay up-to-date on the latest advancements in AI and NLP and know about use-cases, projects and experiences being built with ChatGPT
      The conference call for proposals will be evaluated by ChatGPT itself, ensuring that only the most relevant and informative talks are selected. Don't miss out on this opportunity to learn from the best and take your skills to the next level.

**Comment by chatgpt-conference-admin** [comment]
![image](https://user-images.githubusercontent.com/123183546/213870364-926986f7-fad9-4915-8487-9a04a83d1c3f.png)

**Comment by chatgpt-conference-admin** [comment]
@cgrail

**Comment by cgrail** [comment]
Hi @chatgpt-conference-admin 
I've added the conference to our site in the following PR: https://github.com/tech-conferences/conference-data/pull/5154

Best regards,
Christian
