### ISSUE TITLE
trying to add a UX event to your list and I am getting an error

### ISSUE THREAD

**Issue by UXRCoach** [tech-conferences/conference-data#6057]
Hello,
I tried to add our event to your list (https://confs.tech/conferences/new) and I am getting an error. Can you please add? I am happy to cross-promote your list as well! Thanks,
Jen

https://www.uxrcoach.com/master-course
Feb 18-25, 2024
Big Island Hawaii

**Comment by cgrail** [comment]
Hi @UXRCoach 
I'm sorry that you have not been able to add the conference to our site. However we won't add the event to the list as it is a training event and we try to focus on conferences.

Thanks a lot for your understanding.

Best regards,
Christian
