### ISSUE TITLE
Identifying conferences

### ISSUE THREAD

**Issue by pigulla** [tech-conferences/conference-data#6119]
Hi,

we're working on a small tool for our company to (among other things) help people find conferences they might enjoy. Up until very recently we were using dev.events as data source, but it looks like the developer behind it has disappeared and removed all repositories. As a result, we'd love to pivot to using tech-conferences instead.

I've looked through this repository and it appears that the individual entries don't have an ID. Given how the data is updated via PRs, it is understandable why and I don't see an obvious way of adding one.

Do you have any recommendation or suggestion as to how approach this?

**Comment by cgrail** [comment]
Hi @pigulla 

feel free to use the data from our repo. Yes, we don't have an ID. But you could generate a ID based on the hash of the content:
https://www.npmjs.com/package/js-md5

Another source you could also look into is:
https://github.com/scraly/developers-conferences-agenda

Best regards,
Christian

**Comment by cgrail** [comment]
Then you would need do duplicate detection similar how we do it:
https://github.com/tech-conferences/conference-data/blob/f24df916b9e968e4a4d8fa5ff1ee271a572ae57c/scripts/utils/mergedConferencesReader.js#L17-L20

**Comment by pigulla** [comment]
I'll take a look, thanks!

It'd be nice to have a stable ID at some point, maybe the id of the PR that first creates the conference? :)
