### ISSUE TITLE
Add Colombia Tech Week conference

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6599]
I would like to add [Colombia Tech Week](https://www.colombiatechweek.co/?trk=public_post-text) conference

it will take place in Bogotá, Colombia from August 26 to September 1

![image](https://github.com/tech-conferences/conference-data/assets/25883220/3e5653d4-5d78-4bd2-bfe8-65c560b4b9ec)

**Comment by cgrail** [comment]
Is the Colombia Tech Week really a developer focused event? It seems more like a VC focused event. We usually try to include only developer related events.

**Comment by JuanPabloDiaz** [comment]
Ohh, I wasn't aware it was dev only conf.

Yeah, it's a CV conf.
