### ISSUE TITLE
Add ekoparty

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6605]
Add [EKOPARTY SECURITY CONFERENCE](https://ekoparty.org/)

[EKOPARTY SECURITY CONFERENCE 2024](https://dev.events/conferences/ekoparty-security-conference-2024-oninkjyn)
[Tech](https://dev.events/AM/AR/tech) conference in [Buenos Aires](https://dev.events/AM/AR/Buenos_Aires/tech), [Argentina](https://dev.events/AM/AR/tech)

**Comment by cgrail** [comment]
Added via https://github.com/tech-conferences/conference-data/pull/6609
