### ISSUE TITLE
Add Hands on Testing 2024

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6611]
Aug 28-31 24

[HANDS ON TESTING 2024](https://dev.events/conferences/hands-on-testing-2024-bghfl86q)
[Tech](https://dev.events/AM/MX/tech) conference in [Mexico City](https://dev.events/AM/MX/Mexico_City/tech), [Mexico ](https://dev.events/AM/MX/tech)and [Online](https://dev.events/ON/tech)

![image](https://github.com/tech-conferences/conference-data/assets/25883220/17572cdb-64c2-4ee2-91de-1d77523c31f1)

**Comment by cgrail** [comment]
Added with: https://github.com/tech-conferences/conference-data/pull/6624
