### ISSUE TITLE
Add BSides CDMX 2024

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6612]
![image](https://github.com/tech-conferences/conference-data/assets/25883220/9a9ef03b-ff99-4a00-abf4-7961afa91b1d)

[BSides CDMX 2024](https://bsidescdmx.org/) 

Jul 19, 2024

**Comment by cgrail** [comment]
Added with: https://github.com/tech-conferences/conference-data/pull/6623
