### ISSUE TITLE
Add Jconf Dominicana

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6616]
Jul 19-20 24
![image](https://github.com/tech-conferences/conference-data/assets/25883220/022a09f3-7d30-4b67-a370-b9f60d90096e)

[JCONF DOMINICANA](https://jconfdominicana.org/)
[Tech](https://dev.events/AM/DO/tech) conference in [Santiago de los Caballeros](https://dev.events/AM/DO/Santiago_de_los_Caballeros/tech), [Dominican Republic](https://dev.events/AM/DO/tech)

**Comment by cgrail** [comment]
Added via: https://github.com/tech-conferences/conference-data/pull/6619
