### ISSUE TITLE
Question on contributing - Modifying event details

### ISSUE THREAD

**Issue by robincher** [tech-conferences/conference-data#664]
Hi folks,

Just to check what are the process of modifying existing event details? Forked the repo and open a corresponding Pull request?

Previously i make a submission via the Conf-bot for GopherCon Singapore 2019, but lately the event dates have been changed :).

**Comment by prigara** [comment]
Hi @robincher,
Yes, feel free to send a PR or we can fix the dates ourselves (please let us know the correct dates). Thanks!

**Comment by robincher** [comment]
Ok sure :) , sending a PR now.

I close this issue since the question is answered!
