### ISSUE TITLE
Add Akademy 2024

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6858]
This is a good first issue, perfect for anyone interested in getting started with open source contributions! ✨

If you're new to open source, don't worry! This issue is a great way to jump in. We'll guide you through the process.

To get started, take a look at the [README](https://github.com/tech-conferences/conference-data) – it explains the format for adding conferences. If you have any questions while working on this, feel free to ask! I'm happy to help.

For this specific issue, you'll need to ...

1. Fork the project
2. Create a new branch
3. Add this conference following the conference data structure
   - URL: https://akademy.kde.org/2024/
4. Commit the changes and do the PR.

![image](https://github.com/tech-conferences/conference-data/assets/25883220/bb7ec83a-dd21-4dfe-8094-da8c97992e4f)

**Comment by lostsaber712** [comment]
I would like to work on this issue. Can you assign me to it?

**Comment by JuanPabloDiaz** [comment]
> I would like to work on this issue. Can you assign me to it?

Sure thing! I've assigned it to you @lostsaber712
