### ISSUE TITLE
Bad JSON 2019 ux

### ISSUE THREAD

**Issue by mineralsfree** [tech-conferences/conference-data#692]
2019 ux.json fix pls
![image](https://user-images.githubusercontent.com/23060634/52341208-0ce3fa00-2a23-11e9-8b23-6dc8413edbaf.png)

**Comment by cgrail** [comment]
@mineralsfree Thanks for the feedback. Done in https://github.com/tech-conferences/conference-data/pull/693

We could add a daily build job which checks all json files.

**Comment by mineralsfree** [comment]
@cgrail Thanks for quick fix) Spent half an our to find out what's wrong with my script. Using your json files in educational purpose https://actually-dog.surge.sh

**Comment by cgrail** [comment]
@mineralsfree looks interesting 
Thanks a lot
