### ISSUE TITLE
Json Syntax Check

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6963]
I dont know if we need this but I just found a workflow that will check the syntax of JSON files

[json-syntax-check](https://github.com/JuanPabloDiaz/conference-data/actions/runs/9811809021)

**Comment by cgrail** [comment]
If the syntax is not correct, our current tests will fail. Will this workflow tell you what’s wrong?

**Comment by JuanPabloDiaz** [comment]
> If the syntax is not correct, our current tests will fail. 

We probable don't need it.

> Will this workflow tell you what’s wrong?

kind of: [- /github/workspace/conferences/2023/testing.json: unexpected token at '{' ...](https://github.com/JuanPabloDiaz/conference-data/actions/runs/9818779431/job/27111665414?pr=6)

**Comment by nimzco** [comment]
Since the test would fail like @cgrail mentions, I would just close this issue.

**Comment by JuanPabloDiaz** [comment]
no need
