### ISSUE TITLE
Missing Mastodon title

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#6997]
after completing the form to add a conference, if the user adds a MastodonHandle, the link gets display in the PR but its missing the `Mastodon:`

Example:
![image](https://github.com/tech-conferences/conference-data/assets/25883220/921ba3a6-5c52-4ac7-8e7d-89d0dad899e2)

**Comment by nimzco** [comment]
This should do it! https://github.com/tech-conferences/api.confs.tech/pull/91 :)

**Comment by JuanPabloDiaz** [comment]
It works, thank you!

That techConf(bot) is like black magic to me. 
It will be awesome if I could understand how you guys put it together

**Comment by nimzco** [comment]
Oh, it's actually just a real user with a token to use through the GH API. It's being used by the Rails App in the api.confs.tech repo
