### ISSUE TITLE
Duplicate Conferences - Test should failed

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#7011]
The test didn't fail and mark as duplicate multiple conferences:

- [ ] https://github.com/tech-conferences/conference-data/pull/7007
- [ ] https://github.com/tech-conferences/conference-data/pull/7008
- [ ] https://github.com/tech-conferences/conference-data/pull/7009

Was it because the `URL` and the `name` are not exactly the same in some cases?

**Comment by JuanPabloDiaz** [comment]
I fill out the form with a duplicate conference and the test did failed. it indeed flag it as

 `Error: [name] Found almost identical conference...`

- [ ] https://github.com/tech-conferences/conference-data/pull/7012

**Comment by cgrail** [comment]
Hi @JuanPabloDiaz 

I've created a PR which is using string similarity to recognize duplicates. It looks promising:
https://github.com/tech-conferences/conference-data/pull/7074

Best regards,
Christian

**Comment by cgrail** [comment]
Ok. Found a solution which worked for your test cases:
https://github.com/tech-conferences/conference-data/actions/runs/10147310567/job/28057389678
https://github.com/tech-conferences/conference-data/actions/runs/10147207581/job/28057047257

**Comment by cgrail** [comment]
Now also fixed the EuroStar case:
https://github.com/tech-conferences/conference-data/actions/runs/10148014597/job/28059762426?pr=7007
