### ISSUE TITLE
Duplicate detection is off 

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/conference-data#7202]
Based on some PRs, the logic seems to be a bit off when detecting duplicates conferences. it flags them but they are from previous years.

here is an example: https://github.com/tech-conferences/conference-data/pull/7174/#issuecomment-2312186341

file that needs to be modified: [logTestResult.js](https://github.com/tech-conferences/conference-data/blob/ae56c7bf7e454339b0b65cb3e1a2f5504b506705/scripts/utils/logTestResult.js)

**Comment by cgrail** [comment]
Ok. I've fixed the behavior. The check was correct and the PR which was added as a comment was only a suggestion. I've modified the behavior to only report potential duplicate PRs when it makes sense.
https://github.com/tech-conferences/conference-data/pull/7210

**Comment by JuanPabloDiaz** [comment]
thank you
