### ISSUE TITLE
Add a new conference page broken

### ISSUE THREAD

**Issue by jceb** [tech-conferences/conference-data#7286]
I can't submit a new entry. This is the error message:

![image](https://github.com/user-attachments/assets/126e7c67-ae09-4de5-be53-87a85155d446)

And here's the output from the brower's console:

![image](https://github.com/user-attachments/assets/0cd59026-46cb-40c1-8f5a-6f2f47df9d0d)

**Comment by cgrail** [comment]
I've just tried it out and it worked:
https://github.com/tech-conferences/conference-data/pull/7290

I might be related to your browser settings which might be too strict.
