### ISSUE TITLE
Request: empty array file for topic without conferences

### ISSUE THREAD

**Issue by urmaul** [tech-conferences/conference-data#740]
Context: on Internal hackaton in FlixMobility I've created a tool that retrieves information about conferences and pushes it to slack. You can find it here: https://github.com/flix-tech/confs.tech.push

Right now I'm making http call to current year's json file for specific token to get list of conferences. Sometimes I get http code 404 in response and it may happen because of:
1. I made a typo in topic name so I should fix scheduled script.
2. Repo file structure changed so I should fix the tool.
3. There's no conferences scheduled (like `2019/scala`) and it's ok.

In every case response is same so there's no way to determine whether something's broken or not. This won't be a problem if there's a file with empty array for every year/topic pair.

Also this may possibly fix https://github.com/tech-conferences/confs.tech/issues/429

**Comment by nimzco** [comment]
https://github.com/tech-conferences/conference-data/pull/762 😉 
Thanks again for reporting this! 🙏
